version: "3"
services:
  kali:
    image: sneakykali
    container_name: sneakybeagle
    restart: always
    build:
      context: ./kali
      args:
        SSHPASSWORD: ${SSHPASSWORD}
    ports:
      - "${SSHHOSTPORT}:22"
  nessus:
    image: sneakynessus
    #image: tenableofficial/nessus
    container_name: nessus
    build:
      context: ./nessus
      args:
        ACTIVATION_CODE: ${ACTIVATION_CODE}
        USERNAME: ${USERNAME}
        PASSWORD: ${PASSWORD}
    restart: always
    env_file:
      - .env
    ports:
      - "${NESSUSHOSTPORT}:8834"
  redteam:
    image: sneakyredteam
    container_name: redteam
    build:
      context: ./redteam
      args:
        SSHPASSWORD: ${SSHPASSWORD}
    ports:
      - "${RTSSHHOSTPORT}:22"
    restart: always
    env_file:
      - .env
