name: Docker Infectionmonkey Image CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Docker version
      run: docker --version

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push InfectionMonkey Docker image
      run: |
        cd ./infectionmonkey/
        ./infection_docker.sh
        docker build -t ghcr.io/gorebox-networks/infectionmonkey:latest .
        docker push ghcr.io/gorebox-networks/infectionmonkey:latest
