name: Docker Nessus Image CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Docker Compose version
      run: docker-compose --version

    - name: Copy environment file
      run: cp env .env

    - name: Build and push Nessus container
      run: |
        docker-compose build nessus
        docker tag nessus:latest dvd42/sneakynessus:latest
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker push dvd42/sneakynessus:latest
