name: Docker Quantum Image CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Docker compose version
      run: docker-compose --version
      
    - name: Copy environment file
      run: cp env .env

    - name: Create fake ssh keys
      run: mkdir -p /quantum/files && touch quantum/files/id_rsa quantum/files/id_rsa.pub
      
    - name: Build Quantum container
      run: docker-compose build quantum
