name: Docker Infectionmonkey Image CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Docker version
      run: docker --version
      
    - name: Build infectionmonkey container
      run: cd ./infectionmonkey/ && ./infection_docker.sh
