name: Docker Kali Image CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Docker Compose version
      run: docker-compose --version

    - name: Copy environment file
      run: cp env .env

    - name: Build and push Kali container
      run: |
        docker-compose build kali
        docker tag kali-image:latest ghcr.io/gorebox-networks/kali-image:latest
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login ghcr.io -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker push ghcr.io/gorebox-networks/kali-image:latest
