name: Snyk Redteam Container

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '00 8 * * *'

jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: docker build -t redteam-image -f redteam/Dockerfile .

    - name: Run Snyk to check Docker image for vulnerabilities
      continue-on-error: true
      uses: snyk/actions/docker@v1
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: redteam-image
        args: --file=redteam/Dockerfile --sarif-file-output=snyk.sarif

    - name: Upload Snyk results to GitHub Code Scanni
