name: Update README with installed packages

on:
  pull_request:
    branches:
      - dev
  schedule:
    - cron: '* * * * *'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Update README for Kali tools
      run: |
        pip install PyGithub
        PACKAGES=$(python scripts/get_packages.py -t ${{ secrets.UPLOAD_TOKEN }} -r ${{ github.repository }} -b dev -f kali/Dockerfile)
        python scripts/update_readme.py -t ${{ secrets.UPLOAD_TOKEN }} -r ${{ github.repository }} -b dev -sm "<!---START-MARK-KALI--->" -em "<!---END-MARK-KALI--->" -c "$PACKAGES"

    - name: Update README for Optional Kali tools
      run: |
        pip install PyGithub
        PACKAGES=$(python scripts/get_packages.py -t ${{ secrets.UPLOAD_TOKEN }} -r ${{ github.repository }} -b dev -f kali/files/install_optional.sh)
        python scripts/update_readme.py -t ${{ secrets.UPLOAD_TOKEN }} -r ${{ github.repository }} -b dev -sm "<!---START-MARK-KALI-OPTIONAL--->" -em "<!---END-MARK-KALI-OPTIONAL--->" -c "$PACKAGES"
    
